// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV6KNsIRWnI-7qAbSFQk1a2Rml2ACDYws',
    appId: '1:927827243295:web:440ffb925dff39dc47c02a',
    messagingSenderId: '927827243295',
    projectId: 'login-72aee',
    authDomain: 'login-72aee.firebaseapp.com',
    storageBucket: 'login-72aee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMI-5Hfc0_JHUcvuD1t1T5EefGBBmPXng',
    appId: '1:927827243295:android:f4b63d829452306b47c02a',
    messagingSenderId: '927827243295',
    projectId: 'login-72aee',
    storageBucket: 'login-72aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrId8bHcqWxjpcGZ1Yo9brvspM5Cbx7M',
    appId: '1:927827243295:ios:f5adc247466df7c347c02a',
    messagingSenderId: '927827243295',
    projectId: 'login-72aee',
    storageBucket: 'login-72aee.appspot.com',
    iosClientId: '927827243295-p9rn1b6lit4hhm7ao20bhhcggr0oq93u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMrId8bHcqWxjpcGZ1Yo9brvspM5Cbx7M',
    appId: '1:927827243295:ios:f5adc247466df7c347c02a',
    messagingSenderId: '927827243295',
    projectId: 'login-72aee',
    storageBucket: 'login-72aee.appspot.com',
    iosClientId: '927827243295-p9rn1b6lit4hhm7ao20bhhcggr0oq93u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
